"flamingo_v1_3":
  "Kp_hip": "75"
  "Kp_shoulder": "75"
  "Kp_leg": "75"
  "Kp_wheel": "0"
  "Kd_hip": "0.65"
  "Kd_shoulder": "0.65"
  "Kd_leg": "0.65"
  "Kd_wheel": "0.35"
  "command_3_initial": "0.402"
  "joint_max_torque": "23"
  "wheel_max_torque": "23"

"flamingo_v1_4":
  "Kp_hip": "120"
  "Kp_shoulder": "120"
  "Kp_leg": "120"
  "Kp_wheel": "0"
  "Kd_hip": "2"
  "Kd_shoulder": "2"
  "Kd_leg": "2"
  "Kd_wheel": "0.5"
  "command_3_initial": "0.363"
  "joint_max_torque": "45"
  "wheel_max_torque": "45"

"flamingo_v1_4_1":
  "Kp_hip": "120"
  "Kp_shoulder": "120"
  "Kp_leg": "120"
  "Kp_wheel": "0"
  "Kd_hip": "2"
  "Kd_shoulder": "2"
  "Kd_leg": "2"
  "Kd_wheel": "0.5"
  "command_3_initial": "0.363"
  "joint_max_torque": "45"
  "wheel_max_torque": "45"

"flamingo_edu_v1":
  "Kp_shoulder": "50"
  "Kp_wheel": "0"
  "Kd_shoulder": "1.5"
  "Kd_wheel": "0.2"
  "command_3_initial": "0.0"
  "joint_max_torque": "12"
  "wheel_max_torque": "12"
  "env":
    "obs_dim": "12"
    "action_dim": "4"
    "command_dim": "4"
    "max_lin_vel": "0.5"
    "max_ang_vel": "2.5"
    
