# obs fields: ["dof_pos", "dof_vel", "lin_vel_x", "lin_vel_y", "lin_vel_z", "ang_vel_roll", "ang_vel_pitch", "ang_vel_yaw", "projected_gravity", "height_map", "last_action"]

"flamingo_light_p_v0":
  "stacked_obs_order": ["dof_pos", "dof_vel", "ang_vel_roll", "ang_vel_pitch", "ang_vel_yaw", "projected_gravity", "last_action"]
  "stack_size": 3
  "non_stacked_obs_order": []
  "obs_scales":
    "dof_pos": 1.0
    "dof_vel": 1.0
    "lin_vel_x": 1.0
    "lin_vel_y": 1.0
    "lin_vel_z": 1.0
    "ang_vel_roll": 1.0
    "ang_vel_pitch": 1.0
    "ang_vel_yaw": 1.0
  "command":
    "command_dim": 3
    "command_3_initial": 0.261
  "command_scales":
    "0": 1.0
    "1": 1.0
    "2": 1.0
    "3": 1.0
    "4": 1.0
    "5": 1.0
  "hardware":
    "Kp_shoulder": 50
    "Kd_shoulder": 1.5
    "Kd_wheel": 0.2
    "leg_max_torque": 12
    "wheel_max_torque": 12
    

"flamingo_p_v0":
  "stacked_obs_order": ["dof_pos", "dof_vel", "ang_vel_roll", "ang_vel_pitch", "ang_vel_yaw", "projected_gravity", "last_action"]
  "stack_size": 3
  "non_stacked_obs_order": []
  "obs_scales":
    "dof_pos": 1.0
    "dof_vel": 0.15
    "lin_vel_x": 2.0
    "lin_vel_y": 2.0
    "lin_vel_z": 2.0
    "ang_vel_roll": 0.25
    "ang_vel_pitch": 0.25
    "ang_vel_yaw": 0.25
  "command":
    "command_dim": 4
    "command_3_initial": 0.363
  "command_scales":
    "0": 2.0
    "1": 2.0
    "2": 0.25
    "3": 1.0
    "4": 1.0
    "5": 1.0
  "height_map":
    "size_x": 1.0
    "size_y": 0.6
    "res_x": 15
    "res_y": 9
  "hardware":
    "Kp_hip": 100
    "Kp_shoulder": 100
    "Kp_leg": 150
    "Kd_hip": 1.5
    "Kd_shoulder": 1.5
    "Kd_leg": 2
    "Kd_wheel": 0.5
    "leg_max_torque": 45
    "wheel_max_torque": 45


"humanoid_p_v0":
  "stacked_obs_order": ["dof_pos", "dof_vel", "ang_vel_roll", "ang_vel_pitch", "ang_vel_yaw", "projected_gravity", "last_action", "lin_vel_x", "lin_vel_y", "lin_vel_z"]
  "stack_size": 3
  "non_stacked_obs_order": []
  "obs_scales":
    "dof_pos": 1.0
    "dof_vel": 0.15
    "lin_vel_x": 2.0
    "lin_vel_y": 2.0
    "lin_vel_z": 2.0
    "ang_vel_roll": 0.25
    "ang_vel_pitch": 0.25
    "ang_vel_yaw": 0.25
  "command":
    "command_dim": 4
    "command_3_initial": 1.105
  "command_scales":
    "0": 2.0
    "1": 2.0
    "2": 0.25
    "3": 1.0
    "4": 1.0
    "5": 1.0
  "height_map":
    "size_x": 1.0
    "size_y": 0.6
    "res_x": 15
    "res_y": 9
  "hardware":
    "Kp_hip_pitch": 200
    "Kp_torso": 100
    "Kp_hip_roll": 150
    "Kp_shoulder_pitch": 30
    "Kp_hip_yaw": 150
    "Kp_shoulder_roll": 30
    "Kp_knee": 200
    "Kp_shoulder_yaw": 10
    "Kp_ankle_pitch": 40
    "Kp_elbow_pitch": 20
    "Kp_ankle_roll": 40
    "Kp_elbow_yaw": 10
    "Kd_hip_pitch": 5
    "Kd_torso": 2
    "Kd_hip_roll": 5
    "Kd_shoulder_pitch": 3
    "Kd_hip_yaw": 5
    "Kd_shoulder_roll": 3
    "Kd_knee": 5
    "Kd_shoulder_yaw": 1
    "Kd_ankle_pitch": 4
    "Kd_elbow_pitch": 2
    "Kd_ankle_roll": 4
    "Kd_elbow_yaw": 1
    "hip_roll_joint_max_torque": 200
    "hip_pitch_joint_max_torque": 200
    "hip_yaw_joint_max_torque": 200
    "knee_joint_max_torque": 300
    "torso_joint_max_torque": 200
    "ankle_roll_joint_max_torque": 40
    "ankle_pitch_joint_max_torque": 40
    "shoulder_roll_joint_max_torque": 40
    "shoulder_pitch_joint_max_torque": 40
    "shoulder_yaw_joint_max_torque": 18
    "elbow_pitch_joint_max_torque": 18
    "elbow_yaw_joint_max_torque": 18
